### ISSUE TITLE
Use Github's git-credential-manager instead

### ISSUE THREAD

**Issue by ManfredLange** [hickford/git-credential-oauth#58]
I'd recommend using `git-credential-manager` instead of this package. It's provided by the github ecosystem and cross-platform. It is located here: https://github.com/git-ecosystem/git-credential-manager

Make sure you follow the instructions. Some target platforms such as Linux may require additional steps.

I just wasted a couple of hours with trying to make this - `git-credential-auth` work using the provided instructions.

**Comment by kerhac** [comment]
First off I'm not associated with this project, just passing by and saw this issue and had the desire to leave comment. 

Hi Manfred,

an issue tracker isn't the best place to leave personal recommendations. Better would be a private site or blog. If you wanted to make people aware of the git credential manager, that's already done in the README:

> Git Credential Manager (GCM) is an excellent credential helper with broader functionality. 

The readme also nicely compares both. (0)

I'm also not sure that GCM is from GitHub since its not in their namespace(1). It was initially developed by Microsoft (2) and then moved git-ecosystem later.

Now if you want to be helpful, consider adding some details on the issues you have been having, maybe they can be resolved and the documentation can be updated. Then the time you spent might not have been wasted but helpful for someone else in the future. 

Regards Julian

- 0 <https://github.com/hickford/git-credential-oauth?tab=readme-ov-file#comparison-with-git-credential-manager>
- 1 <https://github.com/github>
- 2 <https://github.com/microsoft/Git-Credential-Manager-for-Windows>

**Comment by hickford** [comment]
Thanks -- I try to be fair and accurate in the [comparison](https://github.com/hickford/git-credential-oauth/blob/main/README.md#comparison-with-git-credential-manager). I personally use both projects.

Please reopen if you have any concrete issues to describe.

**Comment by ManfredLange** [comment]
@hickford No worries. All good.

The main issue I noticed: When you are a member of organizations, then git-credential-auth works correctly for your personal repositories. However, I couldn't find a way to access any of the repositories of the organizations I'm associated with.

Examples:
1. Cloning a private repo that is at https://github.com/ManfredLange/foobar.git works. This is a personal repository.
2. Cloning a private repo that is at https://github.com/RimuTec/foobar.git doesn't authenticate. Instead GitHub returns 404 which it does if permissions are missing. RimuTec is an organization for which I am a github user with the same github id, i.e. "ManfredLange", and where I have full permissions.

I found various suggestions, e.g. including my github id in the URL. However, none of those suggestions worked.

With `git-credential-manager` this scenarios worked just fine without problems.

My platform: Ubuntu 24.04 LTS, git client version 2.43.0

**Comment by hickford** [comment]
Do either of these articles help?

1. https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/approving-oauth-apps-for-your-organization
1. https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps
